# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    main.yml                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: mohamed <mokoucha@students-42heilbronn.de  +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/10/22 03:32:58 by mohamed           #+#    #+#              #
#    Updated: 2022/10/22 03:33:03 by mohamed          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: ahmedsafwat101
          svg_out_path: dist/github-contribution-grid-snake.svg

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
